/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import helper.FacturaSession;
import helper.Helper;
import modelo.Producto;
import modelo.Respuesta;
import modelo.Solicitud;

import javax.swing.*;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;

public class CrearFactura extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(CrearFactura.class.getName());

   
    private final Socket socket;
    private final ObjectOutputStream out;
    private final ObjectInputStream in;

  
    private final String clienteSeleccionado; 

    public CrearFactura(Socket socket, ObjectOutputStream out, ObjectInputStream in) {
        this(socket, out, in, null);
    }

    public CrearFactura(Socket socket, ObjectOutputStream out, ObjectInputStream in, String clienteSeleccionado) {
        this.socket = socket;
        this.out = out;
        this.in = in;
        this.clienteSeleccionado = clienteSeleccionado;

        initComponents();                      
        setTitle("Crear Factura");
        setSize(420, 220);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setContentPane(Panel);      

        
        btnAceptar.addActionListener(e -> verificarYAgregarProducto());
        
    }

    private void verificarYAgregarProducto() {
        try {
            // 1) Leer producto + cantidad desde los componentes del .form
            Object sel = ProductoDropDown.getSelectedItem();
            String productoNombre = (sel == null) ? "" : sel.toString().trim();
            String cantidadStr = CantidadTextField.getText().trim();

            if (productoNombre.isEmpty()) {
                Helper.mostrarMensaje("Debe seleccionar un producto.");
                return;
            }
            if (cantidadStr.isEmpty()) {
                Helper.mostrarMensaje("Debe ingresar la cantidad.");
                return;
            }

            int cantidadSolicitada;
            try {
                cantidadSolicitada = Integer.parseInt(cantidadStr);
            } catch (NumberFormatException nfe) {
                Helper.mostrarMensaje("La cantidad debe ser un número entero.");
                return;
            }
            if (cantidadSolicitada <= 0) {
                Helper.mostrarMensaje("La cantidad debe ser mayor a cero.");
                return;
            }

            
            Object payload = new Object[]{productoNombre, cantidadSolicitada};
            Solicitud solicitud = new Solicitud("verificar_stock", payload);
            out.writeObject(solicitud);
            out.flush();

            
            Respuesta respuesta = (Respuesta) in.readObject();
            if (!respuesta.isExito()) {
               
                Helper.mostrarMensaje(respuesta.getMensaje());
              
                return;
            }

   
            Producto p = (Producto) respuesta.getDatos();

            
            if (clienteSeleccionado != null) {
                FacturaSession.get().setCliente(clienteSeleccionado);
            }
            FacturaSession.get().agregarItem(p, cantidadSolicitada);

      
          
int opcion = JOptionPane.showConfirmDialog(
    this,
    "¿Desea agregar otro producto?",
    "Confirmación",
    JOptionPane.YES_NO_OPTION
);

if (opcion == JOptionPane.YES_OPTION) {
    new CrearFactura(socket, out, in, clienteSeleccionado).setVisible(true);
} else {
    new MostrarFactura(socket, out, in).setVisible(true);
}
dispose();


        } catch (Exception ex) {
            logger.severe("Error en CrearFactura: " + ex.getMessage());
            Helper.mostrarMensaje("Error: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProductoDropDown = new javax.swing.JComboBox<>();
        CantidadTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Crear Factura");

        jLabel3.setText("Seleccione un producto:");

        ProductoDropDown.setBackground(new java.awt.Color(169, 205, 229));
        ProductoDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProductoDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoDropDownActionPerformed(evt);
            }
        });

        jLabel4.setText("Seleccione la cantidad:");

        btnAceptar.setBackground(new java.awt.Color(169, 205, 229));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductoDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProductoDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductoDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoDropDownActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadTextField;
    private javax.swing.JPanel Panel;
    private javax.swing.JComboBox<String> ProductoDropDown;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
